### ISSUE TITLE
Error when linking node executable 

### ISSUE THREAD

**Issue by ddesrude** [opersys/file-explorer-app#1]
After starting the file explorer service i see the following error in the logcat file....

Node standard error: CANNOT LINK EXECUTABLE: cannot locate symbol "sigfillset" referenced by "/data/data/com.opersys.fileexplorer/files/node"...

I am running KITKAT API 19.  Maybe something in the node executable requires a newer version?   Any thoughts on workarounds?

Thanks

**Comment by fdgonthier** [comment]
Thank for you this bug report! I'm glad you took the time to fix that. I think the only workaround here is building a new node binary. It's been a while since I've tasted FE on an older device. The recent upgrade to the binary might have unknowingly broke FE on KK. It shouldn't have. We still love KK and want to support it.

**Comment by ddesrude** [comment]
Hello,

Thanks for your work on the tools on opersys.  My first exposure to them was at andevcon this year in the classes taught by Karim Yaghmour.   I am really looking forward to using them. Since this is my first time using them, I'm not sure when they might of worked with KK.     When you say build a new node binary do you mean from your node repo https://github.com/opersys/node and just build the latest master and copy it into the assets folder?  Or should I go back to a previous release of the node that is known to work on kitkat?  If so which branch.

Thanks in advance for any help

**Comment by ddesrude** [comment]
FYI:   I thought I would try my luck with older prepackaged File Explorer apk's out there for download, and after trying a few different old versions found that with FileExplorer 0.9.0. was able to get past this error.   I was able to login from a webrowser.    However, I did run into other issues where it would show the directory of the android device once and not allow me to select any files with out logging a failure in the browser.  Im guessing the other issues i ran into were because that release may not be as stable.    My goal still is to get your latest app code working on KK.   Just need advice on which version of node i should rebuild.

Thanks

**Comment by fdgonthier** [comment]
I will take care of this in the coming days.

**Comment by fdgonthier** [comment]
I have a new node binary which worked fine when tested quickly in an emulator. I'm going to build new packages and update the repositories in the coming hours.

**Comment by fdgonthier** [comment]
I've pushed a new node.js binary. I will update the .apk tomorrow. I'm having no issue with it in JB in an x86 based emulator. I'll wait for you to return to me before closing this.

**Comment by fdgonthier** [comment]
Actually, the node.js binary is in file-explorer-web!

**Comment by ddesrude** [comment]
I have built your node branch v0.10-android and manually copied the resulting node binary into the assets file directory using adb push onto the installed File Explorer Apps asset directory to replace the old node binary.  I am sure by doing it this way I skipped several steps.  Are you still planning on updating the File Explorer App with the newly built node?   If not I will have more time later today or tomorrow to try a less brute force way of getting the FileExplorerApp to include the newly build node binary.   Thanks for your work on this.

**Comment by ddesrude** [comment]
Oh and with my brute force method it did not work,  which is why I need to look into include the node in the File Explorer App the correct way.

**Comment by fdgonthier** [comment]
That is actually the correct way of changing the binary in your case. The launcher doesn't do any magic before starting the node binary.

I also need to point out that you will have a very limited view or your filesystem unless you launch FE as root or launch it from the ADB shell.

**Comment by fdgonthier** [comment]
Okay I fixed all the apps today. (PE, FE and BE). Closing this.

**Comment by ddesrude** [comment]
Thanks!
